project:
  type: book
  output-dir: docs
  
execute: 
  echo: false

book:
  title: "abram"
  author: "the Bible"
  date: "4/10/2024"
  chapters:
    - index.qmd
    - genese12.qmd
    - genese13.qmd
    - genese14.qmd
    - genese15.qmd
    - genese16.qmd
    - genese17.qmd
    - genese18.qmd
    - genese19.qmd
    - rom4.qmd
    - gal3.qmd
    - heb7.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  epub:
    title: "Abram"
    author: "the Bible"
    toc: true
  
editor: source

